name: build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "macos"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - run: make
      - run: make install
      - run: make test
      - run: chatgpt --help
      - name: Rename executable for ${{ matrix.os }}
        run: mv bin/chatgpt bin/chatgpt-${{ matrix.os }}
      - uses: actions/upload-artifact@v3
        with:
          name: excutable-${{ matrix.os }}
          path: bin/chatgpt-${{ matrix.os }}

  build_windows:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - run: |
          Move-Item -Path 'shard.win.yml' -Destination 'shard.yml' -Force
      - run: shards build --release --debug
        env:
          CHATGPT_NO_READLINE: 1
          CHATGPT_NO_URL: 1
      - uses: actions/upload-artifact@v3
        with:
          name: excutable-windows
          path: bin/chatgpt.exe
