name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '51 3 * * 6'  # Runs at 03:51, only on Saturday

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "macos"]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - run: shards install
      - run: shards build --release --debug
        env :
          CHATGPT_READLINE: "1"
          CHATGPT_BAT: "1"
      - run: crystal spec
      - run: bin/chatgpt version
      - name: Rename executable for ${{ matrix.os }}
        run: mv bin/chatgpt bin/chatgpt-${{ matrix.os }}
      - uses: actions/upload-artifact@v5
        with:
          name: excutable-${{ matrix.os }}
          path: bin/chatgpt-${{ matrix.os }}

  build_windows:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - run: shards build --release --debug --skip-postinstall
      - uses: actions/upload-artifact@v5
        with:
          name: excutable-windows
          path: bin/chatgpt.exe
