name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build_release_x64:
    name: Build Release x64
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: macos-latest
            release_suffix: mac-amd64
          - os: ubuntu-latest
            release_suffix: linux-x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Run Linux Build
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p bin
          chmod 755 bin
          docker run -d --name alpine -v $(pwd):/workspace -w /workspace crystallang/crystal:latest-alpine tail -f /dev/null
          docker exec alpine apk add cmake build-base readline-dev readline-static ncurses-dev ncurses-static ncurses-libs 
          docker exec alpine shards install --without-development --release --static
          docker exec -e CHATGPT_READLINE=1 -e CHATGPT_URL=1 -e CHATGPT_BAT=1 alpine shards build --release --static
          docker exec alpine chmod +x bin/chatgpt
          zip -j bin/chatgpt-linux.zip bin/chatgpt

      - name: Run Mac Build x64
        if: matrix.os == 'macos-latest'
        run: |
          shards install --without-development --release
          shards build --release
          chmod +x bin/chatgpt
          zip -j bin/chatgpt-macos.zip bin/chatgpt
        env:
          CHATGPT_READLINE: 1
          CHATGPT_URL: 1
          CHATGPT_BAT: 1

      - name: Run Windows Build
        if: matrix.os == 'windows-latest'
        run: |
          shards build --release --skip-postinstall
          compress-archive bin/chatgpt.exe bin/chatgpt-windows.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/chatgpt-linux.zip
            bin/chatgpt-macos.zip
            bin/chatgpt-windows.zip
            LICENSE.txt
